### ISSUE TITLE
Le nouveau menu Paramètres n'est pas intuitif

### ISSUE THREAD

**Issue by formotiis** [SachaAngelina/kanssortir#7]
Les dates pickers ne sont pas clair, si tu selectionne des quantités d'heures, je ne veux pas voir d'AM/PM,
pareil, pour la duree de pause je vois 12:45 am par défaut, ça prète a confusion

**Comment by formotiis** [comment]
![image](https://user-images.githubusercontent.com/22288293/122029904-9531f100-cdcd-11eb-9aad-e4fee2a41478.png)
Image for context,
Penser a nos amis les non-francophones

**Comment by AngelinaNaomi** [comment]
Our teams do their best to solve this problem. ASAP
Thank you
